# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('date_hired', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=45)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('contributer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoter', to='wish.Users')),
                ('wish_item', models.ManyToManyField(related_name='wished', to='wish.Users')),
            ],
        ),
    ]
